15.0 mig hr employee calendar planning
OCA/hr pull request #1086
Opened 2022-03-16 20:35 UTC by pegonzalezspesol

Work done:
- Fix tests
- Fix init_hook
- re-generate README.rst
- Fix odoo-pylint lint

2022-04-26 06:08 UTC, victoralmau commented
Please, cherry pick https://github.com/OCA/hr/pull/1094

2022-04-26 17:13 UTC, victoralmau commented
Please, cherry pick https://github.com/OCA/hr/pull/1095#issuecomment-1110021233

2022-04-26 18:16 UTC, victoralmau requested changes
Please, don't remove tests, si very important to validate all use cases.

2022-07-08 15:18 UTC, pegonzalezspesol commented
> Please, don't remove tests, It is very important to validate all use cases.

@victoralmau PR rebased with latests 14.0 status. Can you please have a look?

2022-07-18 09:33 UTC, victoralmau approved these changes
Code review OK.

2022-07-18 09:39 UTC, pedrobaeza commented
/ocabot migration hr_employee_calendar_planning

2022-07-18 09:40 UTC, pedrobaeza commented on hr_employee_calendar_planning/models/resource_calendar.py
> +                        "%(item_name)s is used in %(total_items)s employee(s)."
Can you update at least Spanish translation?

2022-07-18 09:40 UTC, pedrobaeza commented on hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
> +        super(TestHrEmployeeCalendarPlanning, cls).setUpClass()
No need of this diff. It was OK before

2022-08-03 07:07 UTC, victoralmau commented
Can you apply the latest changes to merge it?

2022-08-22 10:13 UTC, victoralmau commented
Please, cherry-pick https://github.com/OCA/hr/pull/1128

2022-08-29 06:58 UTC, victoralmau commented
Superseed by https://github.com/OCA/hr/pull/1138

2022-08-29 06:59 UTC, closed without merging