[15.0][MIG] hr_contract_multi_job
OCA/hr pull request #1202
Opened 2023-03-01 11:20 UTC by yaseentai

2023-03-10 06:57 UTC, Saran440 commented
/obabot migration hr_contract_multi_job

2023-03-10 09:18 UTC, hieulucky111 requested changes

2023-03-10 09:18 UTC, hieulucky111 commented on hr_contract_multi_job/models/hr_contract.py
> +    @api.depends("contract_job_ids")
must be depended on `contract_job_ids.is_main_job`

2023-03-10 09:18 UTC, hieulucky111 commented on hr_contract_multi_job/models/hr_contract.py
> +            if main_job and len(main_job) == 1:
must have `else` while compute function from v13 must always set the value.

2023-03-10 09:18 UTC, hieulucky111 commented on hr_contract_multi_job/security/ir.model.access.csv
> +access_hr_contract_job_manager,hr.contract.job.manager,model_hr_contract_job,hr.group_hr_manager,1,1,1,1
should have read access for normal user? `base.group_user`.

2023-03-23 21:04 UTC, Amjdhassan approved these changes

2023-03-23 21:04 UTC, Amjdhassan approved these changes

2023-03-31 09:09 UTC, hieulucky111 approved these changes
Code review
LGTM

2023-04-21 13:38 UTC, nimarosa commented
/ocabot migration hr_contract_multi_job

2023-04-21 13:39 UTC, nimarosa commented
/ocabot merge nobump

2023-04-21 14:05 UTC, merged