[17.0][MIG] hr_contract_currency
OCA/hr pull request #1357
Opened 2024-06-04 03:21 UTC by baptiste-n42

Work done :

- [x] Update manifest version
- [x] Add thai localization 
- [x] Update view form
- [x] Add warning if using this module with Odoo accounting enterprise enabled

2024-07-17 10:44 UTC, baptiste-n42 commented
@peluko00 @mpascuall Can you please review ?

2024-07-17 11:31 UTC, mpascuall approved these changes
LGTM, tested in runboat

2024-07-18 11:27 UTC, peluko00 approved these changes
LGTM, tested in runboat

2024-07-31 18:53 UTC, pleirb approved these changes
Is it planned to port a version 16 as well?

2024-08-20 06:58 UTC, baptiste-n42 commented
> LGTM, tested in runboat. Is it planned to port a version 16 as well?

I think the migration to v16 could be very easy since the module is fairly small and not that complex.

-----

Do we have a timeline for merging the PR in the stable branch ?

2024-08-20 14:44 UTC, pleirb commented
> > LGTM, tested in runboat. Is it planned to port a version 16 as well?
> 
> I think the migration to v16 could be very easy since the module is fairly small and not that complex.
> 
> Do we have a timeline for merging the PR in the stable branch ?

Yes, that's what I did, I ported this version for v16 but ran into a lot of difficulties with several dependent modules as a comment in issue #167.
How did you resolve the multiple currency issue so you could post accounting entries correctly in version 17?

2024-08-21 02:17 UTC, baptiste-n42 commented
>  How did you resolve the multiple currency issue so you could post accounting entries correctly in version 17?

I didn't.. This module is only for reference, if you're posting in a journal you will use the journal's currency. I don't think you can have a multi-currency journal system, Odoo will just convert foreign currency to the journal currecy based on the latest rate.

2024-09-12 08:30 UTC, baptiste-n42 commented
@peluko00 @mpascuall how can I add this module to issue #1291 modules list ?

2024-09-12 08:36 UTC, mpascuall commented
> @peluko00 @mpascuall how can I add this module to issue #1291 modules list ?

Hi! You can check this link that contains the information you need: https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

2024-09-12 10:12 UTC, baptiste-n42 commented
> Hi! You can check this link that contains the information you need: https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

Hi, yes I read it. So do you need to add this module to the list for this PR to be merged ?

2024-09-12 15:50 UTC, peluko00 commented
> > Hi! You can check this link that contains the information you need: https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
> 
> Hi, yes I read it. So do you need to add this module to the list for this PR to be merged ?

The PSC will add it when review it, don't worry abou that.

2024-12-10 09:14 UTC, dreispt requested changes
Looking at the commit history, I miss the pre 17.0 commits, and I see por 17.0 fix commits, that shouldn't be new in a migration.

2025-05-18 12:15 UTC, closed without merging