[17.0][MIG] hr_employee_medical_examination : Migration to 17.0
OCA/hr pull request #1366
Opened 2024-06-14 09:14 UTC by DorianMAG

supersedes https://github.com/OCA/hr/pull/1305

2024-06-14 09:50 UTC, gaelTorrecillas approved these changes

2024-06-21 08:59 UTC, flotho approved these changes
functionnal review OK
Thanks for the migration

2024-07-02 08:35 UTC, flotho commented
hi @OCA/human-resources-maintainers any chance to have a review and a merge here ?

2024-07-02 09:10 UTC, alexey-pelykh requested changes

2024-07-02 09:10 UTC, alexey-pelykh commented on hr_employee_medical_examination/views/hr_employee_views.xml
> +                    invisible="not can_see_examinations_button"
This should be in the other commit, not `[IMP] hr_employee_medical_examination: pre-commit auto fixes` but `[MIG] hr_employee_medical_examination: Migration to 17.0`

2024-07-02 09:10 UTC, alexey-pelykh commented on hr_employee_medical_examination/views/hr_employee_medical_examination_views.xml
> +                        invisible="state !='pending'"
Same here

2024-08-07 08:57 UTC, DorianMAG commented on hr_employee_medical_examination/views/hr_employee_views.xml
> +                    invisible="not can_see_examinations_button"
Hello @alexey-pelykh ,
Thank you for the code review.

I'm sorry but I am not the owner of this commit. 
How can I proceed to correct it?

Best regards,

2024-11-27 11:37 UTC, DorianMAG commented on hr_employee_medical_examination/views/hr_employee_views.xml
> +                    invisible="not can_see_examinations_button"
@alexey-pelykh 
Hi,
any solution plz?
Regards

2025-05-04 12:15 UTC, closed without merging