[MIG] hr_employee_age: Migration to 17.0.
OCA/hr pull request #1406
Opened 2024-12-06 10:05 UTC by Vang-NguyenPhu

2024-12-06 10:25 UTC, CoraVanga commented
LGTM

2024-12-06 10:28 UTC, huan-tq commented
Useful function!

2024-12-08 04:18 UTC, hitrosol approved these changes
LGTM

2024-12-10 09:31 UTC, dreispt approved these changes

2024-12-13 09:23 UTC, cuongnmtm requested changes
Just a minor change for the version.

2024-12-13 09:23 UTC, cuongnmtm commented on hr_employee_age/__manifest__.py
> +    "version": "17.0.1.0.1",
17.0.1.0.0

2024-12-13 09:47 UTC, cuongnmtm approved these changes

2024-12-18 11:10 UTC, victoralmau requested changes

2024-12-18 11:10 UTC, victoralmau commented on hr_employee_age/models/hr_employee.py
> +            record.age = age
```suggestion
            record.age = record._get_age()
```
The `_get_age()` method already exists in `hr` in v17 so I think we should use it.

2024-12-18 11:10 UTC, victoralmau commented on hr_employee_age/tests/test_hr_employee.py
> +        self.employee_admin.write({"birthday": "1990-05-15"})
```suggestion
from odoo.addons.base.tests.common import BaseCommon


class TestHrEmployee(BaseCommon):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.employee_admin = cls.env.ref("hr.employee_admin")
        cls.employee_admin.write({"birthday": "1990-05-15"})
```

2024-12-18 11:11 UTC, victoralmau requested changes
Code and functional review.

2024-12-20 10:47 UTC, victoralmau approved these changes

2025-03-03 07:45 UTC, Saran440 commented
/ocabot merge nobump

2025-03-03 07:50 UTC, merged