Merge hr_public_holidays to odoo 9
OCA/hr pull request #263
Opened 2016-10-12 09:45 UTC by rami-wafaie

2016-10-12 09:46 UTC, pedrobaeza commented
Change version in all the references (manifest, README...)

2016-10-12 10:00 UTC, pedrobaeza approved these changes
(code review)

2016-10-13 03:38 UTC, feketemihai requested changes
After this, you have my :+1:

2016-10-13 03:38 UTC, feketemihai commented on hr_public_holidays/README.rst
>  ======================
@rami-wafaie Thanks for porting the module, can you please change the bug tracker link version from 8 to 9.

2016-10-13 06:39 UTC, rami-wafaie commented on hr_public_holidays/README.rst
>  ======================
Thanks for your review - Changes are done as requested

2016-10-14 00:38 UTC, andhit-r approved these changes
Code review :+1:

2016-10-14 03:23 UTC, feketemihai approved these changes
@rami-wafaie Thanks for fixing it.

2016-10-14 05:41 UTC, merged