Migration to v9
OCA/hr pull request #268
Opened 2016-10-20 11:45 UTC by damdam-s

2016-10-20 11:45 UTC, damdam-s commented
@gurneyalex ping
#157

2016-10-20 12:38 UTC, leemannd commented
:+1:

2016-10-20 12:51 UTC, simahawk approved these changes
:+1: Overall it's fine. I'd change `<openerp><data>` with `<odoo>`, that's it.

2016-10-20 12:54 UTC, damdam-s commented
thanks @sylvain-garancher for the tip on translations

2016-10-20 13:04 UTC, sylvain-garancher commented
The standard `hr.employee` model has three values for the gender field : Male, Female, or Other.
Maybe you should add Other for `hr.employee.children` accordingly.

Otherwise :+1:

2016-10-21 00:41 UTC, andhit-r requested changes
@damdam-s  thanks for your contributions

Functionality review: Ok (tested on runbot)
Code: Some remarks (see inline comment) and please address https://github.com/OCA/hr/pull/268#pullrequestreview-5061564

2016-10-21 00:41 UTC, andhit-r commented on hr_family/README.rst
Remove

2016-10-21 05:33 UTC, damdam-s commented
@simahawk done
@sylvain-garancher done
@andhit-r I don't see what you want me to remove. `README.rst` file has been updated according OCA guidelines

2016-10-21 06:49 UTC, andhit-r commented
Its https://github.com/OCA/hr/pull/268/files#diff-f495b6dc5b6053b20131ef11b2ca2a5dR17. The **for further information ...**, you dont need that part. But thats minor. So :+1:

2016-10-21 06:51 UTC, damdam-s commented
@andhit-r ok. let's remove it. thanks for explaination

2016-10-21 10:49 UTC, damdam-s commented
@tafaRU @dreispt @dufresnedavid @jgrandguillaume @eLBati @feketemihai as PSC member of this project, can one of you review this or (better) merge it ?
Thanks in advance

2016-10-21 12:13 UTC, feketemihai commented
:+1:

2016-10-21 12:14 UTC, merged

2016-10-21 12:16 UTC, damdam-s commented
@feketemihai thank you !