Update hr_holidays_legal_leave errors.
OCA/hr pull request #289
Opened 2016-11-01 05:24 UTC by feketemihai

Update traceback error with expected singleton on res.company in inverse method, fix comparing apples and oranges in compute method.

2016-11-01 10:33 UTC, pedrobaeza requested changes

2016-11-01 10:33 UTC, pedrobaeza commented on hr_holidays_legal_leave/models/hr_holidays_status.py
> +            rec.is_annual = legal_holiday.id == rec.id
You can compare without the id:
```
rec.is_annual = legalholiday == rec
```

2016-11-01 10:33 UTC, pedrobaeza commented on hr_holidays_legal_leave/models/hr_holidays_status.py
> +                rec.company_id = self.env.user.company_id.id
You shouldn't auto-assign here.

2016-11-01 10:33 UTC, pedrobaeza commented on hr_holidays_legal_leave/models/hr_holidays_status.py
> +            if rec.is_annual:
add here the condition `and rec.company_id`.

2016-11-01 10:48 UTC, pedrobaeza approved these changes

2016-11-10 15:29 UTC, astirpe requested changes

2016-11-10 15:29 UTC, astirpe commented on hr_holidays_legal_leave/models/hr_holidays_status.py
> +                rec.company_id.legal_holidays_status_id = rec.id
`rec.company_id.legal_holidays_status_id = rec`

2017-02-23 08:06 UTC, feketemihai commented
@OCA/human-resources-maintainers Can you have a look at this, please...the error is still present ...in v9 and v10...

2017-02-23 09:55 UTC, astirpe approved these changes
See my comment, is just a minor code review.
Anyway I approve this PR to avoid blocking this bugfix (needed).

2017-02-28 07:42 UTC, gurneyalex commented
@feketemihai there seem to be a conflict in this PR. Could you rebase it please?

2017-02-28 09:00 UTC, feketemihai commented
@gurneyalex Updated...thanks for the review...

2017-02-28 10:30 UTC, dreispt approved these changes

2017-02-28 10:31 UTC, merged