[MIG] 10.0 porting hr_skill
OCA/hr pull request #300
Opened 2016-11-25 15:46 UTC by jlaloux

2017-02-23 08:55 UTC, feketemihai commented on hr_skill/__manifest__.py
@jlaloux Thanks for your contribution, can you please update with small headers, add yourself in the Contributors list...

2017-02-24 06:37 UTC, feketemihai commented
@jlaloux See comments from #299 about the menus and views...

2017-02-24 14:15 UTC, jlaloux commented on hr_skill/__manifest__.py
Hi @feketemihai,
What do you mean by "update with small headers"? I don't see any python filename with big headers.
Thanks

2017-02-24 14:34 UTC, jlaloux commented on hr_skill/__manifest__.py
I supposed this was about updating copyrights?

2017-02-28 07:39 UTC, gurneyalex approved these changes

2017-02-28 13:31 UTC, andhit-r requested changes
@jlaloux you may want to add unittest to pass the codecov test.

2017-03-07 13:13 UTC, jlaloux commented
Test added

2017-03-08 05:32 UTC, feketemihai commented on hr_skill/views/hr_skill.xml
> +              parent="hr.menu_human_resources_configuration"
@jlaloux Hi, thanks for the update, can you add a groups="base.group_no_one" to the menu, to only be visible when you activate the developer mode...

2017-03-13 10:22 UTC, jlaloux commented on hr_skill/views/hr_skill.xml
> +              parent="hr.menu_human_resources_configuration"
Done ;)

2017-03-20 08:39 UTC, dreispt commented on hr_skill/views/hr_skill.xml
> +              groups="base.group_no_one"/>
This menu item will only be visible if the parent Configuration menu item also is.
So IMO this change in unnecessary.

2017-03-20 08:42 UTC, dreispt reviewed
LGTM, only a comment about the menu items.

2017-03-20 08:42 UTC, dreispt commented on hr_skill/__manifest__.py
It's OK as it is: porting a module does not grant copyright on it.

2017-03-20 08:42 UTC, dreispt commented on hr_skill/views/hr_skill.xml
> +              parent="hr.menu_human_resources_configuration"
@feketemihai AFAICT that won't be needed - the menu is only visible if the parent id.

2017-06-12 15:33 UTC, leemannd approved these changes
Thank you for the port.
LGTM
Travis error doesn't seems to be related. 
@jlaloux Could you rebase please?

2017-06-13 01:10 UTC, jcdrubay approved these changes
with a suggestion of variable renaming in the test.

2017-06-13 01:10 UTC, jcdrubay commented on hr_skill/tests/test_hr_skill.py
> +        leadership_skill_id = hr_skill_model.create({
You could remove the suffix _id for `soft_skill_id` and `leadership_skill_id` as those 2 variables represent an instance of object.

2017-06-14 08:20 UTC, dreispt commented
Can you please rebase on current 10.0 branch, to check if we get a green build?

2017-07-13 15:12 UTC, dreispt commented
I'm sorry @jlaloux , but the change set includes files not in the module you are migrating (diffs in 351 files!). If you're having a hard time with `git rebase` I suggest you to start a new clean PR.

2017-10-02 15:31 UTC, gurneyalex requested changes
there was a problem in the rebase, as pointed by @dreispt

2017-10-02 15:44 UTC, leemannd commented
@jlaloux If you need help for the rebase just ping me. You can go back to the original state of this PR with git reflog https://git-scm.com/docs/git-reflog

2017-10-09 14:37 UTC, leemannd commented
I extracted the commits left in his PR to superseed https://github.com/OCA/hr/pull/378.

2017-10-10 11:28 UTC, pedrobaeza commented
Superseeded by #378

2017-10-10 11:28 UTC, closed without merging