add 'hr_holidays_imposed_days' module
OCA/hr pull request #302
Opened 2016-12-02 16:01 UTC by damdam-s

2016-12-05 08:32 UTC, damdam-s commented
@pedrobaeza @feketemihai anyone knows why runbot is red. Seems that I cannot read the build logs :disappointed: 
Thanks for help on this one :smile:

2016-12-05 10:13 UTC, damdam-s commented
aww finally green
Can someone add "Needs Review" label ?

2016-12-05 10:19 UTC, leemannd commented
Code review only. Seems good to me! :+1:

2016-12-05 10:19 UTC, leemannd approved these changes

2016-12-05 10:44 UTC, Garamotte reviewed
LGTM, some minor comments.

2016-12-05 10:44 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    _desc = 'Manage imposed holidays'
`_desc` doesn't exist, you want to use `_description`.

2016-12-05 10:44 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    employee_ids = fields.Many2many('hr.employee')
Please explicitely name the `comodel_name` parameter.

2016-12-05 11:03 UTC, pedrobaeza requested changes
When new employees are added, they don't have the imposed holidays assigned. You should intercept employee create method and assign the corresponding ones.

2016-12-05 11:03 UTC, pedrobaeza commented on hr_holidays_imposed_days/security/ir.model.access.csv
> +"access_hr_holidays_imposed_manager","hr.holidays.imposed_manager","model_hr_holidays_imposed","base.group_hr_manager",1,1,1,1
Line at the end

2016-12-06 08:12 UTC, damdam-s commented
@pedrobaeza fixed. method added to allow easy overriding of the search method.
Currently, `create_date` is used

2016-12-06 08:12 UTC, damdam-s commented
cc @gurneyalex

2016-12-06 08:44 UTC, gurneyalex commented on hr_holidays_imposed_days/models/hr_employee.py
> +        """ add imposed days if a configuration exists """
I like this idea a lot. Very nice touch.

2016-12-06 08:44 UTC, gurneyalex commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    employee_ids = fields.Many2many(comodel_name='hr.employee')
can you add a `help` here mentionning that "if the field is left empty, then the holiday will apply to all employees of the company"?

2016-12-06 08:44 UTC, gurneyalex commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    date = fields.Date(required=True)
a nice addition could be to have a date start and date end to be able to impose a week of holiday (lots of company in France for instance impose the week of Aug. 15 to their employees, or the week between christmas and new year).

2016-12-06 08:44 UTC, gurneyalex commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +                    'date_to': rec.date,
How is the date to datetime conversion handled here? Does odoo take care of specifying a different hour for date_to ? This is important when displaying the holiday in calendar view.

2016-12-06 08:45 UTC, gurneyalex commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    date = fields.Date(required=True)
this could be noted in the README, I'm not requesting this change as part of the review.

2016-12-06 10:24 UTC, gurneyalex requested changes
please add a small test :-)

2016-12-06 11:51 UTC, gurneyalex approved these changes
thanks!

2016-12-06 13:16 UTC, Garamotte requested changes

2016-12-06 13:16 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_employee.py
> +        if imposed:
You can remove the `if` statement, as looping on an empty list works (it does nothing, so doesn't crash), but this is not blocking.

2016-12-06 13:16 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +        to_dt = datetime.datetime.strptime(date_to, DATETIME_FORMAT)
Please use `fields.Datetime.from_string(datetime_object)` instead.

2016-12-06 13:16 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    def onchange_date_to(self):
The two onchange methods are both triggered on the same fields.
I think you should trigger each method on a single field, or merge the two methods.

2016-12-19 22:04 UTC, susport commented on hr_holidays_imposed_days/models/hr_employee.py
> +from openerp import models, api, fields
Order by the import according to the OCA guideline

2016-12-19 22:05 UTC, susport commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    name = fields.Char(required=True)
Suggestion, include the string attribute in the fields

2016-12-20 07:44 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +    name = fields.Char(required=True)
The string is automatically generated from the field's name.
It can be forgotten when you don't want to custimize it.

2017-02-25 13:43 UTC, Garamotte approved these changes
A very minor change.
Otherwise, LGTM :+1:

2017-02-25 13:43 UTC, sylvain-garancher commented on hr_holidays_imposed_days/models/hr_imposed_holidays.py
> +                tools.DEFAULT_SERVER_DATETIME_FORMAT) + datetime.timedelta(
`fields.Datetime.from_string(self.date_from)`

2017-02-27 08:37 UTC, damdam-s commented
Need to add a check (constrain) on date for not being able to record an imposed holiday with date_from < date_to

2018-03-29 12:35 UTC, feketemihai commented
@damdam-s Do you still need it for v9?

2018-03-30 07:59 UTC, damdam-s commented
@feketemihai No, I don't need it on v9 anymore as my customer migrated to v10. Maybe some other people need it?
BTW, you can close it to clean the PR section :smile:

2018-03-30 08:00 UTC, feketemihai commented
@damdam-s Thanks.

2018-03-30 08:00 UTC, closed without merging