Add 10.0 hr_employee_social_media
OCA/hr pull request #317
Opened 2017-02-22 16:18 UTC by leemannd

Add new fields in Employee's form.

2017-02-23 08:49 UTC, leemannd commented
@feketemihai Hello, I'll gladly fix the PR. Did you forget to put a comment?

2017-02-23 08:51 UTC, feketemihai reviewed
I put one direct on the readme file...check it again...

Thanks for the contribution, nice module, but i think we should make it more usefull, adding a model hr.employee.social.media.sites with the name of the site(network, eg. Skype, Facebook,...), a new model that links employee with social media sites and add their account name, by this we are letting people adding the one that they want...beside skype, twitter, whatsapp, there are a lot of other social media network theat people are used to...

2017-02-23 08:51 UTC, feketemihai commented on hr_employee_social_media/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
@leemannd Thanks for the contribution, nice module, but i think we should make it more usefull, adding a model hr.employee.social.media.sites with the name of the site(network, eg. Skype, Facebook,...), a new model that links employee with social media sites and add their account name, by this we are letting people adding the one that they want...beside skype, twitter, whatsapp, there are a lot of other social media network theat people are used to...

2017-02-23 13:44 UTC, leemannd commented on hr_employee_social_media/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
@feketemihai Thanks for the comment. I agree, it could be more usefull in your way.

2017-02-27 11:22 UTC, leemannd commented on hr_employee_social_media/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
@feketemihai I've updated it following your comments. You'll find a first draft to review.

2017-02-27 11:25 UTC, leemannd commented
N.B: Data file is going to be updated to have a sample.

2017-02-27 11:31 UTC, simahawk commented on hr_employee_social_media/models/hr_social_media.py
> +    website = fields.Char(
pls, do not use "website" as field name. It can collide many times. Be more explicit and use something like "social_url".

2017-02-27 12:25 UTC, leemannd commented on hr_employee_social_media/models/hr_social_media.py
> +    website = fields.Char(
@simahawk Updated. & added small sample data

2017-02-28 05:27 UTC, feketemihai requested changes

2017-02-28 05:27 UTC, feketemihai commented on hr_employee_social_media/views/hr_employee_view.xml
> +              <tree>
@leemannd Can you add an editable="bottom" on the tree, even specified only the tree view, it still open the form view...and on the form view it shows the employee Null, so you can assign from one employee a social media account for other employee...

2017-02-28 07:29 UTC, gurneyalex approved these changes
I approve once the small leaked in file is removed.

2017-02-28 07:29 UTC, gurneyalex commented on hr_employee_social_media/security/.~lock.ir.model.access.csv#
> +,dleemann,wrk44.wrk.lsn.camptocamp.com,27.02.2017 13:49,file:///home/dleemann/.config/libreoffice/4;
@leemannd please git rm this file

2017-02-28 08:38 UTC, leemannd commented
@gurneyalex @feketemihai Hello, Thanks for your feedback. It has been updated

2017-03-02 05:55 UTC, feketemihai commented
@leemannd @gurneyalex The PR is ok, but i am wondering, should we leave the Social Media Accounts on the Public Info tab, or we should move them to Personal Info tab...

2017-03-02 05:55 UTC, feketemihai approved these changes

2017-03-02 18:59 UTC, guewen approved these changes

2017-03-02 18:59 UTC, merged

2017-05-09 12:00 UTC, gurneyalex commented
@feketemihai  Could also be a new separate page.