Add 10.0 hr_employee_birth_name
OCA/hr pull request #318
Opened 2017-02-22 16:41 UTC by leemannd

Add new field in employee's personal informations

2017-02-23 08:50 UTC, leemannd commented
@feketemihai Hello, I'll gladly fix the PR. Did you forget to put a comment?

2017-02-23 08:52 UTC, feketemihai commented
@leemannd No i have not forgot...see the comment for the readme file and the website in the manifest...

2017-02-23 08:52 UTC, feketemihai commented on hr_employee_birth_name/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
@leemannd Thanks for your contribution, can you change the readme file, it remained from social media module.

2017-02-23 08:52 UTC, feketemihai commented on hr_employee_birth_name/__manifest__.py
> +    'website': 'http://www.savoirfairelinux.com',
@leemannd Can you check the website...no Savoirfairelinux in the contribution or copyright...

2017-02-23 09:35 UTC, leemannd commented
@feketemihai Thanks for the comment/review. Updated

2017-02-23 09:42 UTC, leemannd commented on hr_employee_birth_name/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Changed

2017-02-23 10:12 UTC, feketemihai approved these changes

2017-02-23 13:57 UTC, yvaucher requested changes

2017-02-23 13:57 UTC, yvaucher commented on hr_employee_birth_name/README.rst
> +If you spotted it first, help us smashing it by providing a detailed and welcomed feedback
Remove the link on feedback (it was removed from template)

2017-02-23 13:57 UTC, yvaucher commented on hr_employee_birth_name/models/hr_employee.py
> +    hr_employee_birth_name = fields.Char(
Why not calling this field simply `birth_name` ?

Like in https://github.com/OCA/partner-contact/tree/7.0/partner_birth_name

2017-02-23 13:58 UTC, yvaucher commented on hr_employee_birth_name/README.rst
> +If you spotted it first, help us smashing it by providing a detailed and welcomed feedback
Please have a look at https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2017-02-23 14:00 UTC, leemannd commented on hr_employee_birth_name/models/hr_employee.py
> +    hr_employee_birth_name = fields.Char(
@yvaucher Didn't saw it. It has been removed since V8. Do you know why?

2017-02-23 14:20 UTC, yvaucher commented on hr_employee_birth_name/models/hr_employee.py
> +    hr_employee_birth_name = fields.Char(
Noone did the migration. But it's okay the other is on partner and this one is on hr_employee

2017-02-24 14:05 UTC, leemannd commented
@yvaucher Updated

2017-02-24 14:26 UTC, yvaucher commented
@leemannd what about the field name ?

2017-02-24 15:54 UTC, leemannd commented
Didn't understood well your comment. I'm going to port the other module. It's still strange that the module has been removed from repo since 8.0

2017-02-28 07:26 UTC, gurneyalex approved these changes

2017-03-01 09:16 UTC, gurneyalex approved these changes

2017-03-01 13:31 UTC, yvaucher approved these changes

2017-03-01 13:31 UTC, merged