[MIG][9.0] hr_period Adapt to date_range
OCA/hr pull request #354
Opened 2017-08-02 11:15 UTC by aheficent

Supersedes this PR https://github.com/OCA/hr/pull/341

Adapted uses the date_range module from server-tools repo. 

### Known issues:
- It's not possible to create date ranges with different number of days using the date_range wizard. That's why periods are created manually for semi-monthly periods.
- The date_range module does not allow to create periods for a single day. This module does. That's why I created this PR: https://github.com/OCA/server-tools/pull/921

2017-09-04 08:45 UTC, mreficent commented
Please rebase the PR  🙂

2017-10-02 16:29 UTC, gurneyalex requested changes
CI is red

2017-10-02 16:31 UTC, gurneyalex commented
Odoo PR will be available in 11 only :-/

2017-10-10 08:15 UTC, lreficent commented
ping @aheficent

2017-12-14 16:13 UTC, mreficent commented on hr_period/models/hr_fiscal_year.py
> +        'Data Range Type',
->Date

2018-03-29 12:36 UTC, feketemihai commented
@aheficent Do you still need this for v9?

2018-03-29 13:32 UTC, aheficent commented
Not really, let's close it. I'll reopen it if anyone is interested.

2018-03-29 13:32 UTC, closed without merging