[10.0] [ADD] hr_payslip_change_state
OCA/hr pull request #356
Opened 2017-08-04 12:21 UTC by nikul-serpentcs

HR Payslip Change State
=======================

This module process payslip batches:

* This module allows to mass change Payslip states
* The module checks if the required action is allowed for each payslip
* If any of the payslips are not in a suitable state a warning message will  pop up and no changes will be made

2017-08-04 12:22 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-08-16 09:06 UTC, LoisRForgeFlow requested changes

2017-08-16 09:06 UTC, lreficent commented on hr_payslip_change_state/__manifest__.py
> +              "Serpent Consulting Services Pvt. Ltd.,",
OCA must be always the last one. But anyway I wouldn't put Serpent as author as what you did here is just a standard migration, and you didn't add any new feature.

2017-08-16 09:10 UTC, lreficent commented
And please, add always the dependencies to other PR or modules not available in OCA.
-----

Depends on https://github.com/OCA/hr/pull/355

2017-10-27 11:10 UTC, nikul-serpentcs commented
@aheficent @lreficent  Could you please review.

2017-10-30 09:16 UTC, aheficent commented
runbot is down

2017-10-30 09:42 UTC, nikul-serpentcs commented
@aheficent Yes, because dependency module `hr_payroll_cancel` is not available.

2018-03-19 10:11 UTC, aheficent commented
@nikul-serpentcs hr_payroll_cancel is available now, would you rebase?

2018-03-22 09:59 UTC, AaronHForgeFlow reviewed
Something is wrong here, 98 commits and 461 files changed.

2018-03-22 10:11 UTC, nikul-serpentcs commented
It is done now! I checked the commits are already rebased to the OCA/hr 10.0

2018-03-30 06:57 UTC, feketemihai commented
@nikul-serpentcs I made a PR, https://github.com/OCA/hr/pull/435 which will solve your travis error, please include that commit, or wait to rebase after is merged.

2018-07-05 15:39 UTC, mreficent commented
Superseeded by https://github.com/OCA/hr/pull/462. This should be closed.

2018-07-05 15:42 UTC, closed without merging