[9.0] hr_public_holidays allow duplicate of year
OCA/hr pull request #377
Opened 2017-10-09 09:26 UTC by Martronic-SA

As it is now, this is not possible to duplicate a year that makes it boring to creates new years.
That PR allows to easily create new years by making the copy of the year and related lines plus one year.
It allows also to deletion the created year if needed.

This will have to be forwarded to 10.0 and 11.0

2017-10-09 21:19 UTC, gurneyalex requested changes

2017-10-09 21:19 UTC, gurneyalex commented on hr_public_holidays/models/hr_public_holidays.py
> +        copy=True
missing comma on line 31

2017-10-10 08:02 UTC, Martronic-SA commented on hr_public_holidays/models/hr_public_holidays.py
> +        copy=True
oh yes, thank you!

2017-10-12 06:49 UTC, Martronic-SA commented
The travis errors are not coming from my PR but underlying in the base public holidays module.
I just want to merge the copy part of my PR, I don't want to review the whole module.
What can I do?

2017-11-27 07:45 UTC, feketemihai commented
@Martronic-SA Can you please fix travis errors, even that is not coming from your PR, tere are just 2 small details. Thanks.

2017-11-29 08:13 UTC, feketemihai commented
@Martronic-SA I changed the file online to pass flake and pylint...hope to be ok...

2017-11-29 09:16 UTC, feketemihai commented
@Martronic-SA Can you add a simple test for copy...otherwise :+1:

2018-03-29 12:32 UTC, feketemihai requested changes
Please add some tests

2021-11-28 12:07 UTC, closed without merging