[MIG] [11.0] Migrate hr_holidays_compute_days to 11.0
OCA/hr pull request #402
Opened 2017-11-13 08:53 UTC by feketemihai

2017-11-13 09:03 UTC, feketemihai commented
Depends on #401

2017-11-14 02:49 UTC, novawish requested changes

2017-11-14 02:49 UTC, novawish commented on hr_holidays_compute_days/models/hr_employee.py
> +from odoo import models, api
import must follows alphabetical order

2017-11-14 02:49 UTC, novawish commented on hr_holidays_compute_days/models/hr_holidays.py
> +from odoo import models, fields, api, _
import must follows alphabetical order

2017-11-14 02:49 UTC, novawish commented on hr_holidays_compute_days/models/hr_holidays_status.py
> +from odoo import models, fields
import must follows alphabetical order

2018-01-20 07:18 UTC, feketemihai commented
The module has been incorporated in hr_public_holidays.

2018-01-20 07:18 UTC, closed without merging