[MIG] [11.0] Migrate hr_payroll_cancel to 11.0
OCA/hr pull request #436
Opened 2018-04-03 17:22 UTC by novawish

2018-04-04 07:45 UTC, jcdrubay requested changes
Approved except for a typo.

2018-04-04 07:45 UTC, jcdrubay commented on hr_payroll_cancel/models/hr_payroll.py
> +                    Refunded Payslip needed to be canceled first!"""))
typo: Replace `needed` by `needs`

2018-04-04 07:45 UTC, jcdrubay commented on hr_payroll_cancel/i18n/fr.po
> +"                    Refunded Payslip needed to be canceled first!"
needs > need

2018-04-04 07:45 UTC, jcdrubay commented on hr_payroll_cancel/i18n/cs_CZ.po
> +"                    Refunded Payslip needed to be canceled first!"
needed > needs

2018-04-11 14:57 UTC, gabrielo77 commented
Why is it writing the state on a single record (`payslip`) instead of the whole RecordSet (`self`) ?

2018-04-11 16:07 UTC, novawish commented
@gabrielo77 Good question, IMO probably the original author's intention is that action always works for only one single record (since the button only appears on form view, and he returned right after the first loop). You are right actually, we should treat it like the whole recordsets no matter what because we were using `api.multi`.

I did a fix based on your PR, may I add you as a contributor for this module also?

2018-04-11 19:42 UTC, gabrielo77 commented
Sure, add me.

I'm currently working on the test cases for this module. Hope I can push it ASAP so we can have this merged.

2018-05-02 19:50 UTC, gustavovalverde commented
This seems ready to merge, or is it codecov a needed check?

2018-06-22 03:43 UTC, hieulucky111 approved these changes

2018-06-22 03:45 UTC, huyly0909 approved these changes
Everything looks ok.

2018-06-22 10:16 UTC, merged