[11.0][MIG] Migrate hr_experience
OCA/hr pull request #437
Opened 2018-04-09 17:11 UTC by ddufresne

2018-04-09 17:37 UTC, ddufresne commented
The travis issue is unrelated with the module.

I proposed a fix anyway in a seperate PR:
https://github.com/OCA/hr/pull/438

2018-04-10 04:46 UTC, feketemihai requested changes

2018-04-10 04:46 UTC, feketemihai commented on hr_experience/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
@ddufresne Thanks for the migration, can you please change to png files.

2018-04-10 04:46 UTC, feketemihai commented on hr_experience/__manifest__.py
> +    "version": "1.0.0",
Update version number

2018-04-10 04:46 UTC, feketemihai commented on hr_experience/views/hr_certification_view.xml
> +                <field name="end_date"/>
Can you add expire field as well in tree view and adapt end_date domain.

2018-04-10 04:46 UTC, feketemihai commented on hr_experience/views/hr_employee_view.xml
> +                                <field name="end_date"/>
The same, expire field and adapt end_date domain.

2018-04-10 11:18 UTC, ddufresne commented
@feketemihai all fixed!

2018-04-10 11:21 UTC, feketemihai commented
@ddufresne Thanks, i will test on runbot when finished.

2018-04-10 11:41 UTC, ddufresne commented
@feketemihai before you test, I am about to add some fixes on the xml views.

2018-04-10 16:10 UTC, ddufresne commented
@feketemihai ok, you may check runbot. Thanks!

2018-04-16 05:54 UTC, feketemihai approved these changes

2018-05-14 22:42 UTC, foutoucour commented
Hello here,
Would you have an ETA on the merge of this PR?

Best,
Jordi

2018-05-15 11:06 UTC, pedrobaeza commented
@foutoucour each PR requires at least 2 approvals. Please make your review for getting this merged.

2018-06-06 18:57 UTC, foutoucour approved these changes

2018-06-06 19:09 UTC, merged