[Mig][11.0]hr_contract_reference-Migration to 11.0.
OCA/hr pull request #456
Opened 2018-07-03 07:33 UTC by Trivedi-Vacha-SerpentCS

[Mig][11.0]hr_contract_reference-Migration to 11.0.

2018-09-05 05:22 UTC, nikul-serpentcs commented on hr_contract_reference/data/hr_contract_sequence.xml
> +    <data noupdate="1">
@Trivedi-Vacha-SerpentCS IMHO Direct use `<odoo noupdate="1">`.

2018-10-01 07:52 UTC, nikul-serpentcs approved these changes
Code Review LGTM

2018-10-01 07:54 UTC, pedrobaeza commented
Can you please squash a bit commit history (specially those that are duplicated message).

2018-10-01 09:03 UTC, Trivedi-Vacha-SerpentCS commented
@pedrobaeza squash bit difficult, because I added preserve also so no need to squash here.

2018-10-01 09:08 UTC, pedrobaeza commented
Well, I'm seeing unrelated commits like "[UPD] Update hr_holidays_public.pot", and also a lot of duplicated commits, like:

![seleccion_001](https://user-images.githubusercontent.com/7165771/46279739-4767f280-c56a-11e8-91aa-5f4b91f942c0.png)

2018-10-01 10:08 UTC, Trivedi-Vacha-SerpentCS commented
@pedrobaeza Squash done

2018-10-01 13:10 UTC, espo-tony requested changes

2018-10-01 13:10 UTC, espo-tony commented on hr_contract_reference/models/hr_contract.py
> +        if vals.get('number', '/') == '/':
I think `number` here should rather be `name`

2018-10-03 05:25 UTC, Trivedi-Vacha-SerpentCS commented
@espo-tony Fixed Code, please add review
@pedrobaeza Squash done, Ready to Merge

2018-10-08 08:30 UTC, espo-tony approved these changes

2018-10-11 17:58 UTC, merged