[11.0][MIG] hr_public_holidays
OCA/hr pull request #465
Opened 2018-07-10 13:51 UTC by mreficent

Superseeds https://github.com/OCA/hr/pull/401.

2018-07-12 11:30 UTC, mreficent commented
Hey everybody! something on Odoo changed that makes a test fail. Previously was all green some months ago in the commit of @feketemihai . My changes didn't affect the tests but the PR is red. I can't find what's the cause or what's wrong, so please, can someone help to fix this?

2018-07-30 14:17 UTC, astirpe requested changes
Thank you for this PR! Please check my comments for the code review.

I personally would prefer a pure porting of this module from https://github.com/OCA/hr/tree/10.0/hr_public_holidays to V11, without adding so much other stuff. The module version =< 10 was meant to be a technical module, useful for being extended for further customization. But with the latest PRs this module is becoming something else.

The calculation of the hours should be delegated to a specific module *hr_holidays_hour*, which migration to V11 is proposed here: #450.

Odoo V12 will have the code for the leave management almost completely rewritten, supporting also the hours calculation, so do we really want to spend so much effort to rewrite the hours management in this module, with the risk to restart all over in V12 (will be released next October :open_mouth:  )?

Anyway I will not block this PR if you have different needs, just think about it.

2018-07-30 14:17 UTC, astirpe commented on hr_holidays_public/models/hr_holidays_public.py
> +from odoo.exceptions import Warning as UserError
Just use:
`from odoo.exceptions import UserError`

2018-07-30 14:17 UTC, astirpe commented on hr_holidays_public/wizards/holidays_public_next_year_wizard.py
> +from odoo.exceptions import Warning as UserError
`from odoo.exceptions import UserError`

2018-07-30 14:17 UTC, astirpe commented on hr_holidays_public/tests/test_holidays_public.py
> +from odoo.exceptions import Warning as UserError
`from odoo.exceptions import UserError, ValidationError`

2018-07-30 14:17 UTC, astirpe commented on hr_holidays_public/views/hr_holidays_public_view.xml
> +                    <field name="year"/>
Could you replace `<field name="year"/>` with `<field name="display_name"/>` here?

2018-07-30 14:17 UTC, astirpe commented on hr_holidays_public/wizards/holidays_public_next_year_wizard.xml
> +                        <div>
There are some trailing spaces in this line. Please check also the other lines.

2018-07-30 14:17 UTC, astirpe commented on hr_holidays_public/models/hr_holidays.py
> +    number_of_hours_temp = fields.Float(
Shouldn't this module inherit from `hr_holidays_hour`?  The module `hr_holidays_hour` already defines those fields for managing the hours. There would be an overall simplification of code by inheriting from `hr_holidays_hour`, for example you could take advantage of methods for the conversion to hours, the onchanges and the views.

Migration of `hr_holidays_hour` to V11 is proposed here: https://github.com/OCA/hr/pull/450.

2018-08-03 10:55 UTC, mreficent commented on hr_holidays_public/models/hr_holidays.py
> +    number_of_hours_temp = fields.Float(
Ok, I will wait then until that module is merged.

- [ ] https://github.com/OCA/hr/pull/450

2018-09-02 17:23 UTC, pedrobaeza commented on hr_holidays_public/models/hr_holidays.py
> +    number_of_hours_temp = fields.Float(
@astirpe I have been reviewing the module `hr_holidays_hour` and the dependency should be just the contrary: to add public holidays, we don't need to make the computation by hours first, but to adjust current Odoo core methods for obtaining the days in float. The hour one should go on top of this. I'm reviewing right now this one and proceed to merge for unlocking this, but I'm available to review any adjustment you need to make over this one for correctly pasting both together. I hope you understand.

2018-09-03 00:43 UTC, pedrobaeza commented
After been thinking about this a lot, this is the best option I have found:

* Leave `hr_holidays_public` with the public holidays definition, the `exclude_public_holidays` field in leave types, and the computation of the days intervals according this definition. This will be transparent for other modules not depending on this one, as the working intervals won't have public holidays and they are able to handle this interval days the way they want.
* Rescue `hr_holidays_compute_days` module for adding day selection helpers (full day selectors for example) and `exclude_rest_days` and `compute_full_days` options on leave types, touching the working days computation the way it's done right now in this PR (although avoiding full method overriding).
* `hr_holidays_hour` can plug together with this in 2 ways:
  * Putting a hook in this second module and depending of it for not repeating computations.
  * Being totally isolated, but repeating some of the computations.

I'm implementing this tomorrow. What do you think?

2018-09-03 08:11 UTC, astirpe commented
@pedrobaeza I would prefer to keep `hr_holidays_hour` independent from other modules, since the idea is to  keep it as a technical module that replaces the days with hours. I understand that we prefer to avoid repetition of code, but in this case I don't see any real benefit in doing that.

2018-09-03 08:13 UTC, pedrobaeza commented
OK, no problem, as stated, you can do it repeating some of the code. Just take a look for not screwing up inheritance for allowing the installation of the 3 of them.

2018-09-03 10:09 UTC, pedrobaeza commented
@mreficent I'm doing the other changes, but thanks for the lint fixup.

2018-09-03 23:35 UTC, pedrobaeza commented
I have finished the adaptation, reducing the code to the minimal and decoupling all modules from each other. I think it has been a good job :smiley: 

For handling module renaming in OpenUpgrade, there's https://github.com/OCA/OpenUpgrade/pull/1509

2018-09-04 07:54 UTC, astirpe requested changes
Review of module  hr_holidays_public only

2018-09-04 07:54 UTC, astirpe commented on hr_holidays_public/views/hr_holidays_public_view.xml
> +                        <field name="country_id"/>
We already have a module that extends this one. Would be nice if you write this block this way (to ease the extensions):

```
                <group>
                    <group name="name">
                        <field name="year"/>
                        <field name="country_id"/>
                    </group>
                    <group name="extra">
                    </group>
                </group>
```

2018-09-04 07:54 UTC, astirpe commented on hr_holidays_public/wizards/holidays_public_next_year_wizard.xml
> +<record id="holidays_public_next_year_wizard_view" model="ir.ui.view">
Could you indent the records more to the right, making this xml consistent with the other views?

2018-09-04 07:54 UTC, astirpe commented on hr_holidays_public/models/hr_holidays_public.py
> +    calendar_leave_id = fields.Many2one(
Why this field was added?

2018-09-04 07:54 UTC, astirpe commented on hr_holidays_public/models/hr_holidays_public.py
> +    calendar_leave_id = fields.Many2one(
Why this field was added?

2018-09-04 07:54 UTC, astirpe commented on hr_holidays_public/models/hr_holidays.py
> +        return super(HrHolidays, obj,)._get_number_of_days(
Could you remove the trailing comma after `obj`?

2018-09-04 08:24 UTC, pedrobaeza commented
Hehe, you have just reviewed the untouched part. Checking the comments...

2018-09-04 08:29 UTC, pedrobaeza commented on hr_holidays_public/models/hr_holidays_public.py
> +    calendar_leave_id = fields.Many2one(
No idea...

2018-09-04 08:32 UTC, pedrobaeza commented
Changes done

2018-09-04 08:38 UTC, astirpe commented
Thanks!

We are not using `hr_holidays_compute_days`, so I think is better to let someone else (more interested) doing the functional review. I could do a code review later when I will have more time.

Module `hr_holidays_public` :+1:

2018-09-04 09:05 UTC, pedrobaeza commented
I think we are going to move forward, and if any problem, we can fill new PRs. This is done for not interfering with your module, so I don't think you will find troubles.

2018-09-04 09:05 UTC, merged