[12.0][ADD] hr_employee_ssn: expose SSN & SIN fields
OCA/hr pull request #493
Opened 2018-10-27 10:35 UTC by alexey-pelykh

2018-10-27 10:36 UTC, alexey-pelykh commented
related to https://github.com/odoo/odoo/pull/28174

2018-10-27 13:07 UTC, pedrobaeza requested changes

2018-10-27 13:07 UTC, pedrobaeza commented on hr_employee_ssn/README.rst
> +This module allows using employee's SSN & SIN fields by exposing them in the user interface.
s/using/to use

2018-10-27 13:07 UTC, pedrobaeza commented on hr_employee_ssn/__manifest__.py
> +        'Allows using employee\'s SSN & SIN fields by exposing them in the'
Better a shorter explanation: `"Show employee's SSN & SIN"

2018-10-27 13:18 UTC, alexey-pelykh commented on hr_employee_ssn/README.rst
> +This module allows using employee's SSN & SIN fields by exposing them in the user interface.
Done

2018-10-27 13:19 UTC, alexey-pelykh commented on hr_employee_ssn/__manifest__.py
> +        'Allows using employee\'s SSN & SIN fields by exposing them in the'
Done

2018-10-27 15:10 UTC, pedrobaeza approved these changes

2018-11-06 13:47 UTC, alexey-pelykh commented
@luistorresm I'd like to request your review as well

2018-11-06 16:13 UTC, luistorresm commented on hr_employee_ssn/views/hr_employee_views.xml
> +        <field name="groups_id" eval="[(6, 0, [ref('hr.group_hr_user') ])]"/>
Hello @alexey-pelykh 

The [page](https://github.com/odoo/odoo/blob/12.0/addons/hr/views/hr_views.xml#L80) where you add this fields already have this group,

Could you remove this?

Regards

2018-11-06 16:53 UTC, gurneyalex approved these changes

2018-11-06 16:55 UTC, merged