[12.0][ADD] hr_employee_document: documents attached to the employee profile
OCA/hr pull request #494
Opened 2018-10-28 19:08 UTC by alexey-pelykh

2018-10-30 04:06 UTC, alexey-pelykh commented
Also hides `google_drive_link` (Employee Documents) field

2018-10-30 04:08 UTC, alexey-pelykh commented
@pedrobaeza I think this PR got lost in your 📫

2018-10-30 08:52 UTC, pedrobaeza commented
I'm helping you in the kick-in in the community, but this is not specially my area of interest and there should be some PRs that I won't review by time (this is all a voluntary effort). You have to find other reviewers for your work, for example reviewing other PRs in the repository or similar repositories and ask in exchange that they review yours.

2018-10-30 08:55 UTC, alexey-pelykh commented
@pedrobaeza got it! Thanks a lot for your help and for the clarification 👍

2018-11-06 13:47 UTC, alexey-pelykh commented
@luistorresm I'd like to request your review as well

2018-11-15 10:36 UTC, alexey-pelykh commented
And @nikul-serpentcs - your review would be much appreciated!

2018-11-24 06:57 UTC, JagdishPanchalSCS requested changes

2018-11-24 06:57 UTC, JagdishPanchalSCS commented on hr_employee_document/models/hr_employee.py
> +            '&', ('res_model', '=', self._name), ('res_id', 'in', self.ids),
Why you pass '&' because its defualt in search method.

2018-11-24 06:57 UTC, JagdishPanchalSCS commented on hr_employee_document/models/hr_employee.py
> +        action['domain'] = str([
No need to pass '&' here because it already default behaviod in domain.

2018-11-24 07:02 UTC, alexey-pelykh commented
@JagdishPanchalSCS thanks for the review, requested changes made, please re-review

2018-11-24 07:04 UTC, nikul-serpentcs approved these changes
Minor change otherwise LGTM

2018-11-24 07:04 UTC, nikul-serpentcs commented on hr_employee_document/views/hr_employee.xml
> +            <xpath expr="//field[@name='create_date']" position="after">
IMO here use `field` directly

2018-11-24 07:08 UTC, alexey-pelykh commented on hr_employee_document/views/hr_employee.xml
> +            <xpath expr="//field[@name='create_date']" position="after">
Good point!

2018-11-24 07:20 UTC, JagdishPanchalSCS approved these changes
Code LGTM

2018-11-26 20:16 UTC, alexey-pelykh commented
@pedrobaeza should we merge it? 👍

2018-11-26 20:29 UTC, merged