[12.0] [MIG] hr_employee_phone_extension
OCA/hr pull request #518
Opened 2018-11-28 13:48 UTC by anandkansagra

Issue [Reference](https://github.com/OCA/hr/issues/479)

2018-11-29 05:53 UTC, nikul-serpentcs approved these changes
If https://github.com/OCA/hr/pull/518#issuecomment-442452417 is fine then Code review LGTM

2018-11-29 06:48 UTC, anandkansagra commented on hr_employee_phone_extension/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
@nikul-serpentcs ,
I think we need to remove the license from `__init__.py` file right?

2019-05-10 20:10 UTC, tbaden requested changes
thanks for the work 👍 
I did a code review:
please use the new fragment [readme](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration)

2019-05-10 20:10 UTC, tbaden commented on hr_employee_phone_extension/views/hr_employee_view.xml
> +    <record id="view_employee_form_inherit_extension" model="ir.ui.view">
aesthetic change (optional):
use original id (view_employee_form)

> prefer naming the inherited view after the original over using a name which follows the guidelines. This eases looking up the original view and other inheritance if they all have the same name.

2019-05-11 05:26 UTC, anandkansagra commented
@tbaden ,
I have made the changes. Could you please look it out?
Thanks

2019-05-15 18:21 UTC, tbaden approved these changes
LGTM

2019-05-16 09:59 UTC, merged