[12.0] [MIG] hr_holidays_settings
OCA/hr pull request #519
Opened 2018-11-29 10:16 UTC by anandkansagra

Issue [Reference](https://github.com/OCA/hr/issues/479)

2018-11-29 11:43 UTC, nikul-serpentcs approved these changes
Code Review LGTM

2019-01-03 00:29 UTC, alexey-pelykh requested changes
Please split README as per https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

2019-01-03 05:36 UTC, anandkansagra commented
Done

2019-01-03 05:41 UTC, alexey-pelykh approved these changes

2019-01-25 15:01 UTC, merged