[MIG] hr_expense_invoice: Migration to 11.0
OCA/hr pull request #525
Opened 2018-12-11 11:13 UTC by cubells

* Standard migration
* convert README.rst to oca fragment

cc @Tecnativa

2018-12-11 12:55 UTC, rafaelbn commented
@cubells are you including this FIX https://github.com/OCA/hr/pull/526 in this PR?

2018-12-11 13:08 UTC, cubells commented
@rafaelbn Yes, I am: from this line https://github.com/OCA/hr/pull/525/files#diff-c36127b1752018180a68bd003f15796aR14

2018-12-11 14:39 UTC, pedrobaeza approved these changes

2018-12-13 05:57 UTC, nikul-serpentcs requested changes
Improve Code

2018-12-13 05:57 UTC, nikul-serpentcs commented on hr_expense_invoice/__manifest__.py
> +    'website': 'https://www.tecnativa.com',
@cubells Replace URL as per [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L11)

2018-12-13 05:57 UTC, nikul-serpentcs commented on hr_expense_invoice/models/hr_expense_sheet.py
> +                raise exceptions.Warning(
@cubells use `UserError`

2018-12-13 05:57 UTC, nikul-serpentcs commented on hr_expense_invoice/views/hr_expense_views.xml
> +            <xpath expr="//field[@name='product_id']" position="after">
@cubells IMO Use Direct `field`

2018-12-13 08:27 UTC, cubells commented
@nikul-serpentcs thanks!

done.

2018-12-13 11:15 UTC, pedrobaeza commented
Merging as @nikul-serpentcs's comments have been honored.

2018-12-13 11:15 UTC, merged