[12.0] [MIG] hr_job_category
OCA/hr pull request #542
Opened 2019-01-20 18:50 UTC by Nikul-Chaudhary

HR Job Employee Categories
==========================
This module was written to extend the functionality of jobs to support tagging employees based on their job positions. For example, all Supervisors could be attached to the Supervisors category.Define which categories a job belongs to in the configuration for the job. When an employee is assigned a particular job the categories attached to that job will be attached to the employee record as well.

2019-02-05 06:11 UTC, alexey-pelykh commented
I think https://github.com/OCA/hr/pull/548 is important to keep track of

2019-02-05 06:13 UTC, alexey-pelykh requested changes

2019-02-05 06:13 UTC, alexey-pelykh commented on hr_job_category/views/hr_view.xml
> +                <label for="category_ids" class="oe_edit_only" groups="base.group_hr_manager"/>
Wait for https://github.com/OCA/hr/pull/548 to be merged or just cherry-pick it's commit to fix the issue mentioned in runbot

2019-02-05 16:57 UTC, Nikul-Chaudhary commented
> I think #548 is important to keep track of

@alexey-pelykh Yes, Sure

2019-03-12 04:38 UTC, i-vyshnevska commented
> > I think #548 is important to keep track of
> 
> @alexey-pelykh Yes, Sure

#548 merget you can pick it

2019-03-12 04:42 UTC, i-vyshnevska requested changes
you doh't keep history please migrate with using https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#technical-method-to-migrate-a-module-from-100-to-110-branch

2019-03-12 04:45 UTC, i-vyshnevska commented
and you add yourself as author if you made some code improvements

2019-03-12 08:30 UTC, pedrobaeza commented
> and you add yourself as author if you made some code improvements

 It would contributor, not author. For being co-author you have to do big code changes/feature addition

2019-04-13 09:41 UTC, Nikul-Chaudhary commented
@alexey-pelykh @i-vyshnevska @pedrobaeza Cherry-Picked commits, Could you please review again.

2019-04-13 09:42 UTC, Nikul-Chaudhary commented
> you doh't keep history please migrate with using https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#technical-method-to-migrate-a-module-from-100-to-110-branch

@i-vyshnevska No need to this, Only Cherry-Pick commits

2019-04-13 09:43 UTC, Nikul-Chaudhary commented
> > and you add yourself as author if you made some code improvements
> 
> It would contributor, not author. For being co-author you have to do big code changes/feature addition

  Noted!!

2019-04-15 07:15 UTC, i-vyshnevska approved these changes

2019-04-26 07:35 UTC, tbaden commented
@alexey-pelykh this looks resolved, could you please check this pr again.

2019-04-26 08:18 UTC, alexey-pelykh approved these changes

2019-05-15 14:30 UTC, jarroyomorales commented on hr_job_category/models/hr.py
> +                _logger.debug("Adding employee tag if job tag doesn't "
Is this message necessary?

2019-05-15 14:34 UTC, jarroyomorales approved these changes
Code review LGTM :+1:

2019-08-14 06:49 UTC, jarroyomorales commented
@pedrobaeza @jbeficent @alexey-pelykh Can we merge this?

2019-08-14 07:15 UTC, pedrobaeza commented
/ocabot merge

2019-08-14 07:59 UTC, closed without merging