[ADD] hr_attendance_modify
OCA/hr pull request #567
Opened 2019-03-14 08:42 UTC by jarroyomorales

2019-03-14 08:45 UTC, pedrobaeza commented
The module name should be ` hr_attendance_modification_tracking` for being more verbose and using nouns, not verbs.

2019-03-14 09:56 UTC, hveficent commented
What is the benefit of registering attendances on chatter. At first sight, it doesn't make me any sense

2019-03-14 10:04 UTC, etobella commented
Well, it is interesting to see who made a change and add the option to add a reason.
If I entered at 10.00 and change it to 8.00 no one can see the change.

2019-03-14 10:08 UTC, HviorForgeFlow approved these changes
Good point :smile: 
Code + functional review
LGTM :+1:

2019-03-14 13:18 UTC, nikul-serpentcs requested changes
Minor Change

2019-03-14 13:18 UTC, nikul-serpentcs commented on hr_attendance_modification_tracking/__manifest__.py
> +    'website': 'www.creublanca.es',
@jarroyomorales URL should be `https://github.com/OCA/hr`

2019-03-14 13:18 UTC, nikul-serpentcs commented on hr_attendance_modification_tracking/__manifest__.py
> +    'demo': [
if no file the remove `key`

2019-05-07 15:50 UTC, etobella commented
@nikul-serpentcs Your comments have been attended. Can you review it again?

2019-05-07 15:51 UTC, etobella approved these changes
LGTM :+1:

2019-05-09 13:51 UTC, jarroyomorales commented
@nikul-serpentcs Is it right now for you?

2019-05-09 16:33 UTC, jbeficent commented
@nikul-serpentcs please in your reviews only mark 'request changes' when the changes are blocking. Otherwise just put a comment like 'small reviews'. We see that your reviews can often block the final approval, specially if you don't follow up quickly on the update of your review.

2019-05-13 06:34 UTC, nikul-serpentcs commented
> @nikul-serpentcs please in your reviews only mark 'request changes' when the changes are blocking. Otherwise just put a comment like 'small reviews'. We see that your reviews can often block the final approval, specially if you don't follow up quickly on the update of your review.

Yes Sure @jbeficent

2019-05-13 06:35 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2019-05-13 11:32 UTC, merged