[14.0][MIG] hr_org_chart_overview
OCA/hr pull request #941
Opened 2020-11-19 09:47 UTC by aphon61bank

Add t-call-assess and t-css for run code, Ready for reviwe.

2020-11-23 15:46 UTC, LoisRForgeFlow reviewed
@aphon61bank Could you clean the commit history and remove the last merge commit? I would also be great if you could split between what are changes from pre-commit and what is the actual migration (see [the migration wiki](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch).

2020-11-23 15:46 UTC, LoisRForgeFlow commented on hr_org_chart_overview/__manifest__.py
> +    "version": "14.0.1.1.0",
just `14.0.1.0.0`

2020-11-23 16:17 UTC, LoisRForgeFlow requested changes
I miss the navigation bar from v13:
![image](https://user-images.githubusercontent.com/23449160/99986569-9fe45480-2daf-11eb-9961-6e94f7c599e5.png)

This is current v14 in runbot:
![image](https://user-images.githubusercontent.com/23449160/99986590-a83c8f80-2daf-11eb-9e24-b6e771bc2776.png)

2021-02-05 10:53 UTC, dreispt commented
Superseded by #953

2021-02-05 10:53 UTC, closed without merging